version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Asia/Singapore
  labels:
  - "dependabot: npm"
  - "pr: dependabot"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
    timezone: Asia/Singapore
  labels:
  - "dependabot: github-actions"
  - "pr: dependabot"
